# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f643e6d6f502106eb41e5ca7f377516"
name = "create-goal"
application_url = "https://pressure-founder-project-washing.trycloudflare.com"
embedded = true
handle = "create-goal"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_discounts"

[auth]
redirect_urls = ["https://pressure-founder-project-washing.trycloudflare.com/auth/callback", "https://pressure-founder-project-washing.trycloudflare.com/auth/shopify/callback", "https://pressure-founder-project-washing.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
